from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol

from foundry_opt.bootstrap.contracts import BootstrapPlan, BootstrapReceipt, ResolvedWeightedObjective


class GitHubReadProtocol(Protocol):
    def read_repository_settings(self, repository: str) -> Mapping[str, object]: ...


class GitHubPlanApplyProtocol(Protocol):
    def plan_changes(self, plan: BootstrapPlan) -> Sequence[Mapping[str, object]]: ...
    def apply_changes(self, plan: BootstrapPlan) -> BootstrapReceipt: ...
    def verify_changes(self, receipt: BootstrapReceipt) -> bool: ...
    def rollback_changes(self, receipt: BootstrapReceipt) -> None: ...


class AzureReadProtocol(Protocol):
    def read_identity_defaults(self) -> Mapping[str, object]: ...


class FoundryReadProtocol(Protocol):
    def read_default_evaluators(self) -> Sequence[Mapping[str, object]]: ...


class RepositoryApplyProtocol(Protocol):
    def write_managed_files(self, plan: BootstrapPlan) -> BootstrapReceipt: ...
    def verify_managed_files(self, receipt: BootstrapReceipt) -> bool: ...
    def rollback_managed_files(self, receipt: BootstrapReceipt) -> None: ...


class EvaluationOnboardingProtocol(Protocol):
    def resolve_objective(self, request: Sequence[Mapping[str, object]]) -> ResolvedWeightedObjective: ...
