from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol

from foundry_opt.bootstrap.contracts import BindingAssessment, BootstrapAction, BootstrapPlan, BootstrapReceipt, ResolvedWeightedObjective


class GitHubInventoryProtocol(Protocol):
    def read_repository_settings(self, repository: str) -> Mapping[str, object]: ...
    def inventory_environments(self, repository: str) -> Sequence[Mapping[str, object]]: ...


class GitHubPlanProtocol(Protocol):
    def plan_changes(self, plan: BootstrapPlan) -> Sequence[BootstrapAction]: ...


class GitHubApplyProtocol(Protocol):
    def apply_changes(self, plan: BootstrapPlan) -> BootstrapReceipt: ...
    def verify_changes(self, receipt: BootstrapReceipt) -> bool: ...
    def rollback_changes(self, receipt: BootstrapReceipt) -> None: ...


class AzureInventoryProtocol(Protocol):
    def inventory_identity(self) -> Mapping[str, object]: ...
    def assess_bindings(self) -> Sequence[BindingAssessment]: ...


class AzurePlanProtocol(Protocol):
    def plan_bindings(self, plan: BootstrapPlan) -> Sequence[BootstrapAction]: ...


class AzureApplyProtocol(Protocol):
    def apply_bindings(self, plan: BootstrapPlan) -> BootstrapReceipt: ...
    def verify_bindings(self, receipt: BootstrapReceipt) -> bool: ...
    def rollback_bindings(self, receipt: BootstrapReceipt) -> None: ...


class FoundryInventoryProtocol(Protocol):
    def inventory_projects(self) -> Sequence[Mapping[str, object]]: ...
    def inventory_evaluators(self) -> Sequence[Mapping[str, object]]: ...


class FoundryPlanProtocol(Protocol):
    def plan_resources(self, plan: BootstrapPlan) -> Sequence[BootstrapAction]: ...


class FoundryApplyProtocol(Protocol):
    def apply_resources(self, plan: BootstrapPlan) -> BootstrapReceipt: ...
    def verify_resources(self, receipt: BootstrapReceipt) -> bool: ...
    def rollback_resources(self, receipt: BootstrapReceipt) -> None: ...


class RepositoryInventoryProtocol(Protocol):
    def inventory_repository(self) -> Mapping[str, object]: ...


class RepositoryPlanProtocol(Protocol):
    def plan_repository_actions(self, plan: BootstrapPlan) -> Sequence[BootstrapAction]: ...


class RepositoryApplyProtocol(Protocol):
    def apply_repository_actions(self, plan: BootstrapPlan) -> BootstrapReceipt: ...
    def verify_repository_actions(self, receipt: BootstrapReceipt) -> bool: ...
    def rollback_repository_actions(self, receipt: BootstrapReceipt) -> None: ...


class EvaluationOnboardingProtocol(Protocol):
    def resolve_objective(self, request: Sequence[Mapping[str, object]]) -> ResolvedWeightedObjective: ...
    def verify_objective(self, objective: ResolvedWeightedObjective) -> bool: ...
    def rollback_objective(self, objective: ResolvedWeightedObjective) -> None: ...
